name: mews_onboarding
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  flutter_ai_toolkit: ^0.9.1
  google_generative_ai: ^0.1.0
  firebase_core: ^3.10.0
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - web/assets/
